server:
  port: 8080
auth:
  expiration: 604800L
  secret: todoAPISecret123
  header: Authorization

#MongoDB Connexion
#spring:
 # data:
  #  mongodb:
   #   database: springTodos
    #  host: localhost
     # port: 27017
